CREATE TABLE `ORDER` (
  `ORDER_ID` int,
  `ORDER_DATE` date,
  `ITEM_ID` int,
  `ITEM_QUANTITY` int,
  `ITEM_TOTAL` double,
  `ITEM_PRICE` double,
  `SALE_FLG` varchar(1),
  `SALE_DISCOUNT` double,
  `STORE_ID` int,
  `CUST_ID` int
);

CREATE TABLE `STORE` (
  `STORE_ID` int,
  `STORE_NUM` int,
  `STORE_NM` varchar(255)
);

CREATE TABLE `STORE_GEO` (
  `STORE_ID` int,
  `AISLE_NUM` int,
  `SECTION_NM` varchar(255),
  `AISLE_GEO_X` int,
  `AISLE_GEO_Y` int
);

CREATE TABLE `ITEM` (
  `ITEM_ID` int,
  `ITEM_NM` varchar(255),
  `ITEM_NM_LONG` varchar(255),
  `AISLE_NUM` int,
  `STORE_ID` int
);

CREATE TABLE `CUSTOMER` (
  `CUST_ID` int,
  `CUST_NM` varchar(255)
);

ALTER TABLE `ITEM` ADD FOREIGN KEY (`ITEM_ID`) REFERENCES `ORDER` (`ITEM_ID`);

ALTER TABLE `STORE` ADD FOREIGN KEY (`STORE_ID`) REFERENCES `ORDER` (`STORE_ID`);

ALTER TABLE `STORE_GEO` ADD FOREIGN KEY (`STORE_ID`) REFERENCES `STORE` (`STORE_ID`);

ALTER TABLE `STORE_GEO` ADD FOREIGN KEY (`AISLE_NUM`) REFERENCES `ITEM` (`AISLE_NUM`);

ALTER TABLE `CUSTOMER` ADD FOREIGN KEY (`CUST_ID`) REFERENCES `ORDER` (`CUST_ID`);
